name: Automated ML Pipeline

on:
    push:
        branches: [ main ]
    
    schedule:
        - cron: '0 0 * * 0'

jobs:
    ci:
        runs-on: ubuntu-latest

        env:
            MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
            MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
            MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2
            
            - name: Setup Python
              uses: actions/setup-python@v6.2.0
              with:
                  python-version: '3.10'
            
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - name: Run tests
              run: |
                  pytest tests/

            - name: Train models
              run: |
                  python -m src.train

    cd:
        needs: ci
        runs-on: ubuntu-latest

        env:
            HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
            MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
            MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
            MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2
            
            - name: Setup Python
              uses: actions/setup-python@v6.2.0
              with:
                  python-version: '3.10'
            
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - name: Retraining models
              run: |
                  python -m src.retrain

            - name: Deploy model
              run: |
                  python -m src.deploy
